task4.2: task4.2.c
	gcc -c task4.2.c
	gcc -o task task4.2.o 
	task
	rm task task4.2.o

tests: tests.c functions.c
	gcc -c functions.c
	gcc -c tests.c
	gcc -o test tests.o
	rm tests.o functions.o

all: task4.2