task6.2: task6.2.cpp 
	g++ -c task6.2.cpp
	g++ -o task task6.2.o
	task
	rm task task6.2.o

tests: tests.cpp functions.cpp
	g++ -c functions.cpp
	g++ -c tests.cpp
	g++ -o test tests.o
	rm tests.o functions.o

all: task6.2