task5.2: task5.2.cpp 
	g++ -c task5.2.cpp
	g++ -o task task5.2.o
	task
	rm task task5.2.o

tests: tests.cpp functions.cpp
	g++ -c functions.cpp
	g++ -c tests.cpp
	g++ -o test tests.o
	rm tests.o functions.o

all: task5.2