task3.2: task3.2.c
	gcc -c task3.2.c
	gcc -o task task3.2.o 
	task
	rm task task3.2.o

tests: tests.c functions.c
	gcc -c functions.c
	gcc -c tests.c
	gcc -o test tests.o
	rm tests.o functions.o

all: task3.2